Repository systopia/de.systopia.remoteevent, pull requests merged in 2024-06, with the labels that each got.

#80 Make custom groups reserved
  CRM/Remoteevent/Upgrader.php
  resources/custom_group_alternative_location.json
  resources/custom_group_remote_registration.json
Labels: bug, status:reviewed and tested

#85 Refactor localization for not changing UF locale for each string
  CRM/Remoteevent/Localisation.php
Labels: enhancement, status:needs review

#81 Add remote spawn action
  Civi/RemoteEvent/Actions/SpawnEvent.php
  Civi/RemoteEvent/CompilerPass.php
  api/v3/RemoteEvent/Spawn.php
  remoteevent.php
Labels: feature, status:reviewed and tested

#87 Fix regression causing additional participants not being registered
  CRM/Remoteevent/RegistrationProfile.php
  Civi/RemoteParticipant/RegistrationEventFactory.php
Labels: bug, status:reviewed and tested
