Repository systopia/de.systopia.remoteevent, pull requests merged in 2024-11, with the labels that each got.

#90 Run tests in GitHub action
  .editorconfig
  .github/workflows/phpunit.yml
  .gitignore
  CRM/Remoteevent/CustomData.php
  api/v3/RemoteEvent/Get.php
  ci/composer.json
  composer.json
  info.xml
  phpcs.xml.dist
  phpstan.ci.neon
  phpstan.neon.dist
  phpstan.neon.template
  phpstanBootstrap.php
  phpunit.xml.dist
  tests/docker-compose.yml
  tests/docker-phpunit.sh
  tests/docker-prepare.sh
  tests/ignored-deprecations.json
  tests/phpunit/CRM/Remoteevent/AnonymousTest.php
  tests/phpunit/CRM/Remoteevent/BasicTest.php
  tests/phpunit/CRM/Remoteevent/CancellationTest.php
  tests/phpunit/CRM/Remoteevent/ContactMatchingTest.php
  tests/phpunit/CRM/Remoteevent/CreateEventTest.php
  tests/phpunit/CRM/Remoteevent/EventCustomFieldTest.php
  tests/phpunit/CRM/Remoteevent/EventFlagsTest.php
  tests/phpunit/CRM/Remoteevent/GetFormTest.php
  tests/phpunit/CRM/Remoteevent/GreetingsTest.php
  tests/phpunit/CRM/Remoteevent/GtacTest.php
  tests/phpunit/CRM/Remoteevent/InvitationTest.php
  tests/phpunit/CRM/Remoteevent/IssuesTest.php
  tests/phpunit/CRM/Remoteevent/ParticipantChangeActivityTest.php
  tests/phpunit/CRM/Remoteevent/ParticipantDataTest.php
  tests/phpunit/CRM/Remoteevent/RegistrationTest.php
  tests/phpunit/CRM/Remoteevent/RegistrationUpdateTest.php
  tests/phpunit/CRM/Remoteevent/SessionTest.php
  tests/phpunit/CRM/Remoteevent/SpeakerTest.php
  tests/phpunit/CRM/Remoteevent/TemplateTest.php
  tests/phpunit/CRM/Remoteevent/TestBase.php
  tests/phpunit/CRM/Remoteevent/UpdateTest_NotImplemented.php
  tests/phpunit/bootstrap.php
  tools/phpcs/composer.json
  tools/phpstan/composer.json
  tools/phpunit/composer.json
Labels: status:needs review

#101 Name the extension consistently by its official name
  CRM/Remoteevent/EventLocation.php
  CRM/Remoteevent/Form/Settings.php
  README.md
  info.xml
  l10n/de.systopia.remoteevent.pot
  l10n/de_DE/LC_MESSAGES/remoteevent.mo
  l10n/de_DE/LC_MESSAGES/remoteevent.po
  tests/phpunit/CRM/Remoteevent/BasicTest.php
  tests/phpunit/CRM/Remoteevent/CreateEventTest.php
  tests/phpunit/CRM/Remoteevent/EventCustomFieldTest.php
  xml/Menu/remoteevent.xml
Labels: enhancement, status:reviewed and tested

#102 Add setting for invitation confirm field default value
  CRM/Remoteevent/Form/Settings.php
  Civi/RemoteParticipant/Event/GetCreateParticipantFormEvent.php
  templates/CRM/Remoteevent/Form/Settings.hlp
  templates/CRM/Remoteevent/Form/Settings.tpl
Labels: feature, status:reviewed and tested
